### ISSUE TITLE
flink quickstart，无法下沉到kafka，提示json解析错误

### ISSUE THREAD

**Issue by letlife** [edp963/wormhole#1096]
com.alibaba.fastjson.JSONException: syntax error, error
        at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:600)
        at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1394)
        at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1360)
        at com.alibaba.fastjson.JSON.parse(JSON.java:165)
        at com.alibaba.fastjson.JSON.parse(JSON.java:175)
        at com.alibaba.fastjson.JSON.parse(JSON.java:144)
        at com.alibaba.fastjson.JSON.parseObject(JSON.java:236)
        at edp.wormhole.ums.UmsSchemaUtils$class.toUms(UmsSchemaUtils.scala:39)
        at edp.wormhole.ums.UmsSchemaUtils$.toUms(UmsSchemaUtils.scala:31)
        at edp.wormhole.ums.UmsCommonUtils$.json2Ums(UmsCommonUtils.scala:57)
        at edp.wormhole.flinkx.util.FlinkSchemaUtils$.findJsonSchema(FlinkSchemaUtils.scala:185)
        at edp.wormhole.flinkx.eventflow.WormholeFlinkxFlowDirective$.getJsonSchema(WormholeFlinkxFlowDirective.scala:50)
        at edp.wormhole.flinkx.eventflow.WormholeFlinkxFlowDirective$.initFlow(WormholeFlinkxFlowDirective.scala:38)
        at edp.wormhole.flinkx.eventflow.WormholeFlinkxStarter$.delayedEndpoint$edp$wormhole$flinkx$eventflow$WormholeFlinkxStarter$1(WormholeFlinkxStarter.scala:38)

**Comment by letlife** [comment]
flink  transformation  使用 CEP ，sink到kafka失败 ，提示json解析错误。。。
