### ISSUE TITLE
spark由2.2.0 切换到 spark.version: 2.4.3 和  json4s.version: 3.5.3时，在启动Stream报错

### ISSUE THREAD

**Issue by OceanMiao** [edp963/wormhole#1134]
java.lang.NoSuchMethodError: org.json4s.JsonAST$JBool$.False()Lorg/json4s/JsonAST$JBool;
	at org.json4s.jackson.JValueDeserializer.deserialize(JValueDeserializer.scala:26)
	at org.json4s.jackson.JValueDeserializer.deserialize(JValueDeserializer.scala:46)
	at org.json4s.jackson.JValueDeserializer.deserialize(JValueDeserializer.scala:39)
	at org.json4s.jackson.JValueDeserializer.deserialize(JValueDeserializer.scala:32)
	at org.json4s.jackson.JValueDeserializer.deserialize(JValueDeserializer.scala:46)
	at org.json4s.jackson.JValueDeserializer.deserialize(JValueDeserializer.scala:39)
	at org.json4s.jackson.JValueDeserializer.deserialize(JValueDeserializer.scala:46)
	at org.json4s.jackson.JValueDeserializer.deserialize(JValueDeserializer.scala:39)
	at wormhole.util.com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1623)
	at wormhole.util.com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1217)
	at org.json4s.jackson.JsonMethods$class.parse(JsonMethods.scala:25)
	at org.json4s.jackson.JsonMethods$.parse(JsonMethods.scala:55)

**Comment by kendev93** [comment]
你好，我也遇到这个问题了，请问最后怎么解决的？
