### ISSUE TITLE
Case classes defined in function bodies are not supported.

### ISSUE THREAD

**Issue by inertance** [edp963/wormhole#1229]
基于0.6.3的版本编译2.4.0的spark，但是在执行flink flow的时候出现Case classes defined in function bodies are not supported.
日志如下：
2020-09-14 15:14:38,135 INFO  org.apache.flink.yarn.cli.FlinkYarnSessionCli                 - Found Yarn properties file under /tmp/.yarn-properties-root.
2020-09-14 15:14:38,135 INFO  org.apache.flink.yarn.cli.FlinkYarnSessionCli                 - Found Yarn properties file under /tmp/.yarn-properties-root.
2020-09-14 15:14:38,976 INFO  org.apache.hadoop.yarn.client.RMProxy                         - Connecting to ResourceManager at fbi-local-03/10.0.165.3:8032
2020-09-14 15:14:39,123 INFO  org.apache.flink.yarn.cli.FlinkYarnSessionCli                 - No path for the flink jar passed. Using the location of class org.apache.flink.yarn.YarnClusterDescriptor to locate the jar
2020-09-14 15:14:39,123 INFO  org.apache.flink.yarn.cli.FlinkYarnSessionCli                 - No path for the flink jar passed. Using the location of class org.apache.flink.yarn.YarnClusterDescriptor to locate the jar
2020-09-14 15:14:39,217 INFO  org.apache.flink.yarn.AbstractYarnClusterDescriptor           - Found application JobManager host name 'fbi-local-06' and port '39141' from supplied application id 'application_1592979353214_0553'
Starting execution of program
{"flow_name":"kafka.instance.database.namespace.*.*.*-clickhouse.sink.sink.counter.*.*.*","kafka_input":{"kafka_base_config":{"group_id":"kafka.instance.database.namespace.*.*.*-clickhouse.sink.sink.counter.*.*.*","brokers":"fbi-local-08:9092","kerberos":false,"session.timeout.ms":30000,"group.max.session.timeout.ms":60000,"key.deserializer":"org.apache.kafka.common.serialization.StringDeserializer","value.deserializer":"org.apache.kafka.common.serialization.StringDeserializer","auto.offset.reset":"earliest"},"kafka_topics":[{"topic_name":"database","topic_partition":"0:42,1:0,2:0,3:0,4:0,5:0,6:0,7:1,8:0,9:0,10:0,11:0"}]},"kafka_output":{"feedback_topic_name":"wormhole_feedback","brokers":"fbi-loacl-08:9092,fbi-local-09:9092","kerberos":false},"commonConfig":{"stateBackend":"hdfs://fbi-local-03:8020/flink-checkpoints"},"zookeeper_address":"fbi-local-05:2181,fbi-local-06:2181,fbi-local-04:2181","udf_config":[],"feedback_enabled":false,"feedback_state_count":100,"feedback_interval":30,"kerberos":false} --------------wh config
{"protocol":{"type":"directive_flow_start"},"schema":{"namespace":"kafka.instance.database.namespace.*.*.*","fields":[{"name":"directive_id","type":"long","nullable":false},{"name":"stream_id","type":"long","nullable":false},{"name":"job_id","type":"long","nullable":false},{"name":"ums_ts_","type":"datetime","nullable":false},{"name":"data_type","type":"string","nullable":false},{"name":"data_parse","type":"string","nullable":true},{"name":"sink_namespace","type":"string","nullable":false},{"name":"consumption_protocol","type":"string","nullable":false},{"name":"sinks","type":"string","nullable":false},{"name":"swifts","type":"string","nullable":true},{"name":"config","type":"string","nullable":false}]},"payload":[{"tuple":[4,1,"1","20200914151437000","ums","","clickhouse.sink.sink.counter.*.*.*","eyJpbml0aWFsIjogdHJ1ZSwgImluY3JlbWVudCI6IHRydWUsICJiYXRjaCI6IHRydWV9","eyJzaW5rX2Nvbm5lY3Rpb25fdXJsIjogImpkYmM6Y2xpY2tob3VzZTovL2ZiaS1sb2NhbC0xMTo4MTIzL3NpbmsiLCJzaW5rX2Nvbm5lY3Rpb25fdXNlcm5hbWUiOiAiYWRtaW4iLCJzaW5rX2Nvbm5lY3Rpb25fcGFzc3dvcmQiOiAiYWRtaW4iLCJzaW5rX3RhYmxlX2tleXMiOiAiaWQiLCJzaW5rX291dHB1dCI6ICIiLCJzaW5rX2Nvbm5lY3Rpb25fY29uZmlnIjogIiIsInNpbmtfcHJvY2Vzc19jbGFzc19mdWxsbmFtZSI6ICJlZHAud29ybWhvbGUuc2lua3MuY2xpY2tob3VzZXNpbmsuRGF0YTJDbGlja2hvdXNlU2luayIsInNpbmtfc3BlY2lmaWNfY29uZmlnIjoge30sInNpbmtfcmV0cnlfdGltZXMiOiAiMyIsInNpbmtfcmV0cnlfc2Vjb25kcyI6ICIzMDAifQ==","eyJ0aW1lX2NoYXJhY3RlcmlzdGljIjoicHJvY2Vzc2luZ190aW1lIiwicHVzaGRvd25fY29ubmVjdGlvbiI6W10sImRhdGFmcmFtZV9zaG93IjoiZmFsc2UiLCJhY3Rpb24iOiJabXhwYm10ZmMzRnNJRDBnYzJWc1pXTjBJR2xrTEdOdmRXNTBLQ29wSUdGeklHTnVkQ0JtY205dElHNWhiV1Z6Y0dGalpUcz0ifQ==","eyJwYXJhbGxlbGlzbSI6MSwiY2hlY2twb2ludCI6eyJlbmFibGUiOmZhbHNlLCJjaGVja3BvaW50X2ludGVydmFsX21zIjozMDAwMDAsInN0YXRlQmFja2VuZCI6ImhkZnM6Ly9mbGluay1jaGVja3BvaW50In19"]}]} --------------flow start

------------------------------------------------------------
 The program finished with the following exception:
org.apache.flink.client.program.ProgramInvocationException: The main method caused an error.
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:546)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:421)
	at org.apache.flink.client.program.ClusterClient.run(ClusterClient.java:427)
	at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:813)
	at org.apache.flink.client.cli.CliFrontend.runProgram(CliFrontend.java:287)
	at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:213)
	at org.apache.flink.client.cli.CliFrontend.parseParameters(CliFrontend.java:1050)
	at org.apache.flink.client.cli.CliFrontend.lambda$main$11(CliFrontend.java:1126)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1836)
	at org.apache.flink.runtime.security.HadoopSecurityContext.runSecured(HadoopSecurityContext.java:41)
	at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1126)
Caused by: org.json4s.package$MappingException: scala.Predef$.refArrayOps([Ljava/lang/Object;)Lscala/collection/mutable/ArrayOps; Case classes defined in function bodies are not supported.
	at org.json4s.reflect.package$.fail(package.scala:95)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder$$anonfun$9.apply(Reflector.scala:118)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder$$anonfun$9.apply(Reflector.scala:118)
	at scala.util.control.Exception$Catch$$anon$2.apply(Exception.scala:260)
	at scala.util.control.Exception$Catch$$anon$2.apply(Exception.scala:258)
	at scala.util.control.Exception$Catch.apply(Exception.scala:227)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.constructorsAndCompanion(Reflector.scala:118)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.result(Reflector.scala:209)
	at org.json4s.reflect.Reflector$.createDescriptor(Reflector.scala:53)
	at org.json4s.reflect.Reflector$$anonfun$describe$1.apply(Reflector.scala:48)
	at org.json4s.reflect.Reflector$$anonfun$describe$1.apply(Reflector.scala:48)
	at org.json4s.reflect.package$Memo.apply(package.scala:36)
	at org.json4s.reflect.Reflector$.describe(Reflector.scala:48)
	at org.json4s.Extraction$$anonfun$extract$7.apply(Extraction.scala:409)
	at org.json4s.Extraction$$anonfun$extract$7.apply(Extraction.scala:408)
	at org.json4s.Extraction$$anonfun$customOrElse$1.apply(Extraction.scala:637)
	at org.json4s.Extraction$$anonfun$customOrElse$1.apply(Extraction.scala:637)
	at scala.PartialFunction.applyOrElse(PartialFunction.scala:123)
	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:122)
	at scala.PartialFunction$$anon$1.applyOrElse(PartialFunction.scala:253)
	at org.json4s.Extraction$.customOrElse(Extraction.scala:637)
	at org.json4s.Extraction$.extract(Extraction.scala:408)
	at org.json4s.Extraction$.extract(Extraction.scala:40)
	at org.json4s.ExtractableJsonAstNode.extract(ExtractableJsonAstNode.scala:21)
	at edp.wormhole.util.JsonUtils$class.json2caseClass(JsonUtils.scala:35)
	at edp.wormhole.util.JsonUtils$.json2caseClass(JsonUtils.scala:29)
	at edp.wormhole.flinkx.eventflow.WormholeFlinkxStarter$.delayedEndpoint$edp$wormhole$flinkx$eventflow$WormholeFlinkxStarter$1(WormholeFlinkxStarter.scala:34)
	at edp.wormhole.flinkx.eventflow.WormholeFlinkxStarter$delayedInit$body.apply(WormholeFlinkxStarter.scala:29)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:388)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at edp.wormhole.flinkx.eventflow.WormholeFlinkxStarter$.main(WormholeFlinkxStarter.scala:29)
	at edp.wormhole.flinkx.eventflow.WormholeFlinkxStarter.main(WormholeFlinkxStarter.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:529)
	... 12 more
我检查了WormholeFlinkxStarter.scala 里面并没有定义case class 但是这个类继承了App特质，并且调用了JsonUtils.json2caseClass,我不清楚这里的泛型以及delayInit是否会导致Case classes defined in function bodies are not supported. 我用的scala版本是2.11.12  另外如果不自己编译的话，用官网提供的tar包，默认是scala2.11.8 在执行flink flow 时也会出现问题,java.lang.NoSuchMethodError: scala.Predef$.refArrayOps([Ljava/lang/Object;)Lscala/collection/mutable/ArrayOps; 我把scala 的sdk切换为2.11.8 并没有得到改善

**Comment by inertance** [comment]
问题已解决，flink的scala版本不一致导致的
