### ISSUE TITLE
When I follow Quick Start I got error

### ISSUE THREAD

**Issue by lordk911** [edp963/wormhole#698]
2018-08-21 10:31:30 [Executor task launch worker for task 174] ERROR edp.wormhole.batchflow.BatchflowMainProcess[32] - SendAlert do classifyRdd,one data has error,row:(data_increment_data.kafka.kafkatest.wormhole_test.wormhole_t.*.*.*,{"id": 5，"name": "test"，"phone":"18074546423"，"address": "Beijing"，"time": "2017-12-22 10:00:00"})
com.alibaba.fastjson.JSONException: syntax error, position at 0, name id
	at com.alibaba.fastjson.parser.DefaultJSONParser.parseObject(DefaultJSONParser.java:589)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1335)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1301)
	at com.alibaba.fastjson.JSON.parse(JSON.java:148)
	at com.alibaba.fastjson.JSON.parse(JSON.java:139)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:212)
	at edp.wormhole.common.WormholeUtils$.dataParse(WormholeUtils.scala:88)
	at edp.wormhole.common.WormholeUtils$.jsonGetValue(WormholeUtils.scala:77)
	at edp.wormhole.batchflow.BatchflowMainProcess$$anonfun$edp$wormhole$batchflow$BatchflowMainProcess$$getClassifyRdd$1$$anonfun$apply$11.apply(BatchflowMainProcess.scala:158)
	at edp.wormhole.batchflow.BatchflowMainProcess$$anonfun$edp$wormhole$batchflow$BatchflowMainProcess$$getClassifyRdd$1$$anonfun$apply$11.apply(BatchflowMainProcess.scala:153)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at edp.wormhole.batchflow.BatchflowMainProcess$$anonfun$edp$wormhole$batchflow$BatchflowMainProcess$$getClassifyRdd$1.apply(BatchflowMainProcess.scala:153)
	at edp.wormhole.batchflow.BatchflowMainProcess$$anonfun$edp$wormhole$batchflow$BatchflowMainProcess$$getClassifyRdd$1.apply(BatchflowMainProcess.scala:148)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:800)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:800)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD$$anonfun$7.apply(RDD.scala:337)
	at org.apache.spark.rdd.RDD$$anonfun$7.apply(RDD.scala:335)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1092)
	at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1083)
	at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:1018)
	at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1083)
	at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:809)
	at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:335)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:286)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by lordk911** [comment]
I'm sorry ,It's about my test data error. I write wrong comma . Thank you very much.
