### ISSUE TITLE
wormhole integration dbus

### ISSUE THREAD

**Issue by timxim** [edp963/wormhole#730]
目前wormhole0.5版本集成DBus发现问题：
2018-08-28 16:30:04 [riderActorSystem-akka.actor.default-dispatcher-2] ERROR edp.rider.rest.persistence.dal.NamespaceDal[78] - synchronize dbus namespace failed
org.json4s.package$MappingException: Expected collection but got JObject(List((status,JInt(1006)), (message,JString(无法找到token)))) for root JObject(List((status,JInt(1006)), (message,JString(无法找到token)))) and mapping Seq[SimpleDbus]
        at org.json4s.reflect.package$.fail(package.scala:96)
        at org.json4s.Extraction$CollectionBuilder.mkCollection(Extraction.scala:362)
        at org.json4s.Extraction$CollectionBuilder.result(Extraction.scala:384)
        at org.json4s.Extraction$.extract(Extraction.scala:339)
        at org.json4s.Extraction$.extract(Extraction.scala:42)
        at org.json4s.ExtractableJsonAstNode.extract(ExtractableJsonAstNode.scala:21)
        at org.json4s.jackson.Serialization$.read(Serialization.scala:50)
        at edp.wormhole.common.util.JsonUtils$class.json2caseClass(JsonUtils.scala:35)
        at edp.wormhole.common.util.JsonUtils$.json2caseClass(JsonUtils.scala:29)
        at edp.rider.rest.persistence.dal.NamespaceDal$$anonfun$getDbusFromRest$1$$anonfun$apply$2.apply(NamespaceDal.scala:66)
        at edp.rider.rest.persistence.dal.NamespaceDal$$anonfun$getDbusFromRest$1$$anonfun$apply$2.apply(NamespaceDal.scala:66)
        at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
        at scala.util.Try$.apply(Try.scala:192)
        at scala.util.Success.map(Try.scala:237)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
**conf/application.conf 配置如下：**
dbus.namespace.rest.api.url = ["http://x.x.x.x:5090/v1/keeper/tables/riderSearch"]
期盼回复，谢谢！

**Comment by swallowjy** [comment]
@timxim 0.5.1-beta版本支持集成DBus0.5.x以下版本，下一版本会支持DBus0.5版本。
